version: "3"

services:
  app:
    build: 
      context: ""
      args:
        - ENVIRONMENT=local
    ports:
      - "8080:8080"
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - ./app:/usr/src/app
      - ./models:/usr/src/models
    environment:
      - db_host=postgresql://postgres:postgres@postgresdb:5432/postgres

    # The database needs to be run before the main.py file
    depends_on:
      - postgresdb

# Testing environment
  app-test:
    build:
      context: ""
      args:
        - ENVIRONMENT=test
    volumes:
      - .:/usr/src
  

# PostgreSQL
  postgresdb:
    image: postgres:14.6
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env-local
    volumes:
      - db_pg:/var/lib/postgresql/data

volumes:
  db_pg: 

  
